import { printToFileAsync } from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { Trip } from '../db/queries/trips';

interface PDFConfig {
  driverName: string;
  orgName: string;
  vehicleName: string;
  licensePlate: string;
  startDate: string;
  endDate: string;
  totalKm: number;
  businessKm: number;
  personalKm: number;
  totalDeductible: number;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function generateHtmlTemplate(trips: Trip[], config: PDFConfig): string {
  const tripRows = trips
    .map(
      (trip) => `
      <tr>
        <td>${escapeHtml(trip.date)}</td>
        <td>${escapeHtml(trip.start_address ?? '-')}</td>
        <td>${escapeHtml(trip.end_address ?? '-')}</td>
        <td>${trip.km.toFixed(2)}</td>
        <td>${escapeHtml(trip.category)}</td>
        <td>${escapeHtml(trip.purpose ?? '-')}</td>
        <td>${trip.rate_used != null ? `$${trip.rate_used.toFixed(4)}` : '-'}</td>
        <td>${trip.deductible != null ? `$${trip.deductible.toFixed(2)}` : '-'}</td>
      </tr>`
    )
    .join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 40px;
          color: #333;
          font-size: 12px;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          border-bottom: 2px solid #1976D2;
          padding-bottom: 20px;
        }
        .header h1 {
          color: #1976D2;
          margin: 0 0 5px 0;
          font-size: 24px;
        }
        .header p {
          margin: 2px 0;
          color: #666;
        }
        .summary {
          display: flex;
          justify-content: space-between;
          margin-bottom: 30px;
          background: #f5f5f5;
          padding: 15px;
          border-radius: 5px;
        }
        .summary-item {
          text-align: center;
        }
        .summary-item .value {
          font-size: 18px;
          font-weight: bold;
          color: #1976D2;
        }
        .summary-item .label {
          font-size: 10px;
          color: #666;
          text-transform: uppercase;
        }
        .details {
          margin-bottom: 20px;
        }
        .details p {
          margin: 3px 0;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 20px;
        }
        th {
          background: #1976D2;
          color: white;
          padding: 8px 5px;
          text-align: left;
          font-size: 10px;
        }
        td {
          padding: 6px 5px;
          border-bottom: 1px solid #eee;
          font-size: 10px;
        }
        tr:nth-child(even) {
          background: #fafafa;
        }
        .footer {
          margin-top: 30px;
          text-align: center;
          color: #999;
          font-size: 10px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Mileage Report</h1>
        <p>${escapeHtml(config.orgName)}</p>
        <p>${escapeHtml(config.startDate)} to ${escapeHtml(config.endDate)}</p>
      </div>

      <div class="details">
        <p><strong>Driver:</strong> ${escapeHtml(config.driverName)}</p>
        <p><strong>Vehicle:</strong> ${escapeHtml(config.vehicleName)} (${escapeHtml(config.licensePlate)})</p>
      </div>

      <div class="summary">
        <div class="summary-item">
          <div class="value">${config.totalKm.toFixed(1)} km</div>
          <div class="label">Total Distance</div>
        </div>
        <div class="summary-item">
          <div class="value">${config.businessKm.toFixed(1)} km</div>
          <div class="label">Business</div>
        </div>
        <div class="summary-item">
          <div class="value">${config.personalKm.toFixed(1)} km</div>
          <div class="label">Personal</div>
        </div>
        <div class="summary-item">
          <div class="value">$${config.totalDeductible.toFixed(2)}</div>
          <div class="label">Total Deductible</div>
        </div>
      </div>

      <h2>Trip Details</h2>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>From</th>
            <th>To</th>
            <th>Distance (km)</th>
            <th>Category</th>
            <th>Purpose</th>
            <th>Rate</th>
            <th>Deductible</th>
          </tr>
        </thead>
        <tbody>
          ${tripRows}
        </tbody>
      </table>

      <div class="footer">
        <p>Generated by Mileage Tracker on ${new Date().toLocaleDateString()}</p>
        <p>Total Trips: ${trips.length}</p>
      </div>
    </body>
    </html>
  `;
}

/**
 * Generate a PDF report from trips and share it via the system share dialog.
 */
export async function generateAndSharePDF(
  trips: Trip[],
  config: PDFConfig
): Promise<void> {
  const html = generateHtmlTemplate(trips, config);

  const { uri } = await printToFileAsync({ html });

  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Share Mileage Report',
    UTI: 'com.adobe.pdf',
  });
}
